tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
  - name: react-js
    command: |
      cd frontend-react-js
      npm i    
  - name: GITPOD_IP
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source "$THEIA_WORKSPACE_ROOT/backend-flask/bin/rds-update-sgr-rule"
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - gitpod.gitpod-desktop
    - ms-azuretools.vscode-docker
    - formulahendry.docker-explorer
    - henriiik.docker-linter
    - formulahendry.docker-extension-pack
    - donjayamanne.githistory
    - mhutchie.git-graph
    - eamodio.gitlens
    - GitHub.copilot
    - GitHub.github-vscode-theme
    - PKief.material-icon-theme
    - vscode-icons-team.vscode-icons
    - Atishay-Jain.All-Autocomplete
    - amazonwebservices.aws-toolkit-vscode
    - streetsidesoftware.code-spell-checker
    - GitHub.copilot-labs
    - oderwat.indent-rainbow
    - nickdemayo.vscode-json-editor
    - esbenp.prettier-vscode

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public